Support reading from gzipped files
CMSgov/hpt-validator-cli pull request #17
Opened 2024-08-10 17:04 UTC by Myles1

Thanks for publishing and maintaining this project. Super helpful stuff!
Feel free to just close this PR if you don't want it. No biggie either way :)

## One line description of your change (less than 72 characters)
Support reading from `.csv.gz` and `.json.gz` files.

## Problem

Explain the context and why you're making that change. What is the problem
you're trying to solve? In some cases there is not a problem and this can be
thought of being the motivation for your change.

I'm compressing the data files locally and need to unzip them before I can run the `hpt-validator-cli`. This just lets us read gzipped files directly.

## Solution

Describe the modifications you've done.

Allow reading directly from gzipped data files.

## Result

What will change as a result of your pull request? Note that sometimes this
section is unnecessary because it is self-explanatory based on the solution.

Some important notes regarding the summary line:

- Describe what was done; not the result
- Use the active voice
- Use the present tense
- Capitalize properly
- Do not end in a period — this is a title/subject
- Prefix the subject with its scope

## Test Plan

(Write your test plan here. If you changed any code, please provide us with
clear instructions on how you verified your changes work.)

Create a gzipped data file 
`$gzip my_file.json`
You should now have a file named `my_file.json.gz`
Run `hpt-validator-cli` on that new file.
Ensure the results are the same as they were on the unzipped file.

2024-09-03 17:54 UTC, shaselton-usds commented
@Myles1 Thank you so much for your pull request and your patience. 

I think this definitely makes sense and is a value-add. 

The one thing that I would request to be changed is to avoid adding the `.gz` as an additional format to be passed into the CLI. It really isn't a different format as it is a compression of the acceptable formats. Would it be possible to update the PR to auto detect whether the acceptable formats are compressed via `.gz` and then run through the expected business logic to validate the file appropriately?

Once updated we'll gladly accept this PR with much thanks!

2024-09-03 17:56 UTC, shaselton-usds requested changes

2024-09-03 17:56 UTC, shaselton-usds commented on src/commands.ts
> +type FileFormat = "csv" | "json" | "json.gz" | "csv.gz"
Let's remove `.gz` extensions as acceptable format types.

2024-09-03 17:56 UTC, shaselton-usds commented on src/commands.ts
> +  const isGzipped = path.extname(filepath).toLowerCase() === ".gz"
Potentially hoist this check up to determine if one of the acceptable formats is gzipped.

2024-09-03 17:56 UTC, shaselton-usds commented on src/index.ts
> +        "csv.gz",
Remove these new options as acceptable formats as the main branch of logic would handle this internally.

2024-12-12 16:37 UTC, shaselton-usds commented
Closing this PR in favor of this new one that covers the same functionality: https://github.com/CMSgov/hpt-validator-cli/pull/28

2024-12-12 16:37 UTC, closed without merging

2024-12-14 19:09 UTC, Myles1 commented
@shaselton-usds Thank you and sorry about my lack of response here. Glad to see the new PR!