supporting gzip checks
CMSgov/hpt-validator-cli pull request #28
Opened 2024-12-12 16:35 UTC by shaselton-usds

Slightly changing how to support gzipped file based on this PR: https://github.com/CMSgov/hpt-validator-cli/pull/17

Thank you @Myles1

2024-12-12 16:35 UTC, shaselton-usds commented on src/commands.ts
> +  inputStream: fs.ReadStream | NodeJS.ReadableStream,
@mint-thompson the PR is pretty small and straightforward, but I did want to look at this specifically to see if it introduces any potential risk.

2024-12-13 14:19 UTC, mint-thompson requested changes
The code change looks good! We should probably also update the README to explain that gzipped files ending with `.gz` can be used, and that files ending with `.csv.gz` or `.json.gz` will have their file type detected.

2024-12-19 19:42 UTC, mint-thompson requested changes
Thanks for adding a section to the readme! I have a suggestion for the new section that hopefully clarifies the interaction of `.gz` detection and `.csv`/`.json` detection.

2024-12-19 19:42 UTC, mint-thompson commented on README.md
> +The two current allowable file formats for the HPT MRFs are CSV and JSON. The CLI will auto detect the file format passed into the tool and will run the appropriate validator for that file. The CLI c
I'm trying to work out the best way to explain the two layers of file type detection going on here, since `something.gz` will be decompressed, but needs to have a format specified on the command line. But, `something.csv.gz` or `something.json.gz` will have both parts of the file type detected automatically. Maybe something like this?
```suggestion
The two current allowable file formats for the HPT MRFs are CSV and JSON. The CLI will auto detect the file format passed into the tool for files that end with `.csv` or `.json` and will run the appropriate validator for that file. The CLI can also detect files compressed by gzip. Files ending with the `.gz` extension will be decompressed before validation. These file format detections can be combined, so files ending with `.csv.gz` or `.json.gz` will be decompressed and validated as CSV or JSON, respectively. For other files ending with `.gz`, use the `-f` option described above.
```

2025-01-02 20:55 UTC, mint-thompson approved these changes
hooray for gzip!

2025-01-02 20:57 UTC, merged